### ISSUE TITLE
Use a "small" dictionary for commands instead the whole one.

### ISSUE THREAD

**Issue by Maikell84** [TalAter/annyang#115] opened 2015-06-08 11:11 UTC
Hello!

When I put debug mode on, I see, that although I have set a list of commands, the software searches __the whole__ english dictionary! Even though I only need about 20 Words. 
E.g. I say "register" it recognizes:

    annyang.min.js:6 Speech recognized: Rochester
    annyang.min.js:6 Speech recognized: Register
    annyang.min.js:6 Speech recognized: regester
    annyang.min.js:6 Speech recognized: registered

I think the recognition would be more "stable" if the software only would look in a small dictionary instead of the whole one. (Even though you can't "dictate" a text anymore, but for a simple command-based webapplication this is not needed at all. )
Is it somehow possible to create a very simple dictionary, with only the 20 commands that I need?

A "dirty" workaround, that I did to improve the recognition is, to say "register" many times, always more or less "sloppy". Then I checked the debug output (A great help btw ;)) for every recognized word, and put it in the command list, like so:

    //Add several versions of "register"
	'register': function() {  registerNewUser(); },
	'Red Lobster': function() {  registerNewUser(); },
	'Register': function() {  registerNewUser(); },
	'Red Rooster': function() {  registerNewUser(); },
	'regester': function() {  registerNewUser(); },
	'registrar': function() {  registerNewUser(); },
	'Rochester': function() {  registerNewUser(); },
	'magista': function() {  registerNewUser(); },
	'Magisto': function() {  registerNewUser(); },
	'Rochester': function() {  registerNewUser(); },
	'richest': function() {  registerNewUser(); },
	'Registeel': function() {  registerNewUser(); },
	'Rochester': function() {  registerNewUser(); },

Unfortunately this does not help, with some "variable" commands that I need. (Commands that the user itself defines via an input field)

So is there already a possibility to change the dictionary to a user defined one? If not, will there be one? ;)
Best regards
Michael

**Comment by rmilesson** [comment] 2015-09-23 14:48
Annyang only integrates with Chromes native voice recognition. The dictionary being used is on Chromes side of it all.

**Comment by TalAter** [comment] 2016-03-31 16:32
Duplicate of #11 

I really hope to be able to support this. Need to investigate the browser support for it (it is in the spec).

**Closed by TalAter** 2016-03-31 16:32 UTC
