### ISSUE TITLE
Electron Speech Recognition is repeatedly stopping and starting

### ISSUE THREAD

**Issue by DemSquirrel** [TalAter/annyang#237] opened 2016-11-13 18:58 UTC
I get this error 

> Speech Recognition is repeatedly stopping and starting. See http://is.gd/annyang_restarts for tips.

 when i try activate my commands

My code 

    window.annyang = require('./node_modules/annyang/dist/annyang.min.js');
    annyang.debug();
    // Define sample command
    var commands = {
      'hello': function() {
        console.log("Hello Sir");

      }
    };
    // Add our commands to annyang
    annyang.addCommands(commands);
    // Start listening. You can call this here, or attach this call to an event, button, etc.
    annyang.start();

This is in the main html file

**Comment by peterdillon** [comment] 2016-11-14 16:47
This may be a duplicate of:
https://github.com/TalAter/annyang/issues/194

**Closed** 2017-05-24 12:57 UTC
