### ISSUE TITLE
Bulk commands loop

### ISSUE THREAD

**Issue by torosushi** [TalAter/annyang#333] opened 2018-03-13 22:40 UTC
Due to total of commands, I would like to add the commands dynamically inside the loop but it is not working.

This is what I have so far:

if(annyang){
	var menuName=[],comFunc={},commands={};
	menuName= ["Katsu Don", "Ramen Don", "Tempura Noodle", "Karaage Curry", "Katsu Curry", "Tempura Curry", "Tempura Don", "Kaisendon", "Vege Don", "Salmon Don", "Chicken Don", "Beef Don", "(Set) Chicken", "(Set) Ramen", "(Set) Sashimi", "(Set) Sushi", "(Set) Udon", "Miso", "Rice", "Seaweed"]
	console.log(menuName);
	for(var v=0; v<menuName.length; ++v){
		var comName=menuName[v]; 
		commands[v]={comName:comFunc[v]};
		comFunc[v]=function(){
			alert(comName);
		}
	}console.log(commands);
	annyang.addCommands(commands);
	annyang.start();
}

How to get it work? Thank you.

**Comment by TalAter** [comment] 2018-03-15 14:34
Duplicate of #332

**Closed by TalAter** 2018-03-15 14:34 UTC
